Proxy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Proxy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'proxy.views.home', name='home'),
)

urlpatterns += staticfiles_urlpatterns()

proxy/models.py
from django.db import models

# Create your models here.

proxy/forms.py
from django import forms


class URLForm(forms.Form):
    url = forms.CharField()

proxy/views.py
from django.shortcuts import render, redirect
from django.template import RequestContext
from django.http import HttpResponse
from lxml import html
import requests
from proxy.forms import URLForm


def download_page(url):
    r = requests.get(url)
    contents = r.headers['content-type'].split(';')
    content = contents[0]
    if content.startswith('image'):
        page = r
    else:
        page = r.text
    return page, content


def get_title(doc):
    title = doc.find('.//title')
    if title is not None:
        return title.text


def rewrite_link(link):
    link = link.replace('&', '%26')
    if link.startswith('javascript'):
        return link
    return '/?q=' + link


def replace_links(doc, url):
    doc.make_links_absolute(url)
    doc.rewrite_links(rewrite_link)
    return doc


def get_head(doc):
    head = html.tostring(doc.head)
    head = head.decode('utf-8')
    body_list = head.split('\n')[1:-1]
    head = '\n'.join(body_list)
    return head


def get_body(doc):
    body = html.tostring(doc.body)
    body = body.decode('utf-8')
    body_list = body.split('\n')[1:-1]
    body = '\n'.join(body_list)
    return body


def check_url(url):
    if not url:
        return
    if url[:7] != 'http://' and url[:8] != 'https://':
        return 'http://' + url
    else:
        return url


def home(request):
    if request.method == 'POST':
        form = URLForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']
            return redirect('/?q=' + url)
    else:
        url = request.GET.get('q')
        url = check_url(url)
        if url:
            page, content = download_page(url)
            if content == 'text/html':
                form = URLForm()
                doc = html.document_fromstring(page)
                title = get_title(doc)
                doc = replace_links(doc, url)
                head = get_head(doc)
                body = get_body(doc)
                context = {'form': form, 'head': head, 'body': body, 'title': title}
                return render(request, 'page.html', context, context_instance=RequestContext(request))
            else:
                return HttpResponse(page, content_type=content)
        else:
            form = URLForm()
            return render(request, 'home.html', {'form': form}, context_instance=RequestContext(request))

templates/home.html
<!doctype html>
<html lang="pl">
<head>{% load staticfiles %}
    <meta charset="UTF-8">
    <title>Proxy</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container fill">
    <div class="middle">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <form action="/" class="form-horizontal" role="form" method="post">{% csrf_token %}{% load bootstrap %}
                    <div class="col-sm-10">
                        {{ form.url | bootstrap_inline }}
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-success">Go</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $('#id_url').val('http://')
</script>
</body>
</html>

templates/page.html
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Proxy - {{ title }}</title>
    {{ head|safe }}
</head>
<body>
{{ body|safe }}
</body>
</html>